name: continuous-deployment
on:
  push:
    branches:
      - main
    paths:
      - code/**

concurrency: deployment-${{ github.ref }}

jobs:
  deployment-stg:
    timeout-minutes: 30
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Invoke training workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: aml-train
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
            '{ "deploy-to": "${DEPLOY_ENV}"}'
        env:
          DEPLOY_ENV: "Staging"

  deployment-prd:
    needs: [deployment-stg]
    timeout-minutes: 30
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Invoke training workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: aml-train
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
            '{ "deploy-to": "${DEPLOY_ENV}"}'
        env:
          DEPLOY_ENV: "Production"
