name: continuous-integration
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  push:
    branches:
      - master

jobs:
  code_style:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      - uses: pre-commit/action@v2.0.3

  unittests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: code_style
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Run unittests
        run: |
          python -m pytest ""

