name: aml-deploy

on:
  workflow_dispatch:
    inputs:
      deploy-to:
        description: "Environment to deploy to. Development|Staging|Production"
        required: false
        default: "Development"
      model-name:
        description: "Name of the model to deploy to"
        required: true
      model-version:
        description: "Version of the model to deploy to"
        required: false
        default: "1"
      az-workspace:
        description: 'Azure workspace'
        required: false
        default: "lc-onboarding"
      az-resource-group:
        description: "Azure resource group"
        required: false
        default: "lc-test"
      repository:
        description: "The repository from which the slash command was dispatched"
        required: false
      comment-id:
        description: "The comment-id of the slash command"
        required: false
      issue-number:
        description: "The issue number from which the slash command was created"
        required: false

concurrency: deploy-refs/pull/${{ github.event.inputs.issue-number }}/head

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.deploy-to }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/env_setup
        with:
          event_name: ${{ github.event_name }}
          issue_number: ${{ github.event.inputs.issue-number }}
          az_workspace: ${{ github.event.inputs.az-workspace }}
          az_resource_group: ${{ github.event.inputs.az-resource-group }}

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
        if: ${{ github.event.inputs.issue-numer }} != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          issue-number:  ${{ github.event.inputs.issue-number }}
          body: |
            Deployment submitted.
            [Click here to see the deploy run output](${{ steps.vars.outputs.run-url }}

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: CLI and workspace setup
        run: |
          az extension add -n azure-cli-ml
      - name: Deploy model
        run: |
          # --dc .cloud/.azure/Development_aks.json
          az ml model deploy --name irisservice --model ${model_name}:${model_version} \
           --compute-target aks-cluster-new --compute-type AKS \
           --entry-script score.py --conda-file environment.yml\
           --source-directory code/deploy/ --workspace-name ${workspace} --resource-group ${group}
          ls -la .cloud/.azure
        env:
          model_name:  ${{ github.event.inputs.model-name }}
          model_version: ${{ github.event.inputs.model-version }}
          workspace: ${{ github.event.inputs.az-workspace }}
          group: ${{ github.event.inputs.az-resource-group }}

      - name: Create comment
        if: ${{ github.event.inputs.issue-numer }} != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.inputs.issue-number }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          body: |
            scoring-endpoint: ${{ steps.aml_deploy.outputs.service_scoring_uri}}
            swagger-uri: ${{ steps.aml_deploy.outputs.service_swagger_uri}}
