name: slash-command

on:
  issue_comment:
    types: [created]

jobs:
  # This is the dispatch for slash commands in the repo
  slash_command:
    runs-on: ubuntu-latest
    steps:      
    
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
      
      - name: Fetch remote ref
        run: git fetch origin +refs/pull/*:refs/pull/*
        
      - name: debug
        run: | 
          git show-ref 
          echo "---"
          git ls-remote
        
      
      - name: Slash Command Dispatch
        id: slash_command
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ github.token.GITHUB_TOKEN }}
          commands: |
            train
            deploy
          permission: write
          issue-type: pull-request
          dispatch-type: workflow
          static-args: |
            repository=${{ github.repository }}
            issue-number=${{ github.event.issue.number }}
            comment-id=${{ github.event.comment.id }}
