# Actions train a model on Azure Machine Learning
name: aml-train
on:
  push:
    branches:
      - main
  # todo: uncomment
#    paths:
#      - code/**

  workflow_dispatch:
    inputs:
      repository:
        description: "The repository from which the slash command was dispatched"
        required: false
      comment-id:
        description: "The comment-id of the slash command"
        required: false
      issue-number:
        description: "The issue number from which the slash command was created"
        required: false
      az-workspace:
        description: 'Azure workspace'
        required: false
        default: "lc-onboarding"
      az-resource-group:
        description: "Azure resource group"
        required: false
        default: "lc-test"
      kernel:
        description: "Kernel type for SVM model"
        required: false
        type: choice
        default: "linear"
        options:
          - "linear"
          - "rbf"
          - "sigmoid"
          - "poly"
      penalty:
        description: "Penalty for SVM model"
        required: false
        default: "0.1"
      model-name:
        description: "Name of the trained model"
        required: false
        default: "iris_model"

concurrency: train-refs/pull/${{ github.event.inputs.issue-number }}/head

jobs:
  train:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v3
      
    - name: Setup
      uses: ./.github/actions/env_setup
      with:
        event_name: ${{ github.event_name }}
        issue_number: ${{ github.event.inputs.issue-number }}
        az_workspace: ${{ github.event.inputs.az-workspace }}
        az_resource_group: ${{ github.event.inputs.az-resource-group }}

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure workspace and resource group
      id: aml_workspace
      run: |
       az extension add -n azure-cli-ml
       az configure --defaults workspace=$WS group=$RG
      env:
        WS: ${{ github.event.inputs.az-workspace }}
        RG: ${{ github.event.inputs.az-resource-group }}

    - name: Submit training run
      run: |
        az ml run submit-script \
        --conda-dependencies ./code/train/environment.yaml \
        --experiment-name iris_experiment \
        --source-directory ./code/train \
        --ct cpu-cluster train.py --kernel rbf --penalty 1.0 --model_name ${MODEL_NAME}
      env:
        KERNEL: ${{ github.event.inputs.kernel }}
        PENALTY: ${{ github.event.inputs.penalty }}
        MODEL_NAME: ${{ github.event.inputs.model-name }}

    - name: Create comment for training metrics
      if: ${{ github.event.inputs.issue-numer }} != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        issue-number: ${{ github.event.inputs.issue-number }}
        body: |
           Train script submitted, 
           [Click here to see the deploy run output](${{ steps.vars.outputs.run-url }})

    - name: Trigger deploy
      if: ${{ github.event_name }} == 'push'
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: aml-deploy
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        inputs: |
          { "deploy-to": "${DEPLOY_ENV}", "model-name": "${MODEL_NAME}"}
      env:
        DEPLOY_ENV: "Production"
        MODEL_NAME: ${{ github.event.inputs.model-name }}
