# Actions train a model on Azure Machine Learning
name: aml-train
on: 
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      repository:
        description: "The repository from which the slash command was dispatched"
        required: true
      comment-id:
        description: "The comment-id of the slash command"
        required: true
      issue-number:
        description: "The issue number from which the slash command was created"
        required: false
      az-workspace:
        description: 'Azure workspace'
        required: false
        default: ""
      az-resource-group:
        description: "Azure resource group"
        required: false
        default: ""


concurrency: deployment-refs/pull/${{ github.event.inputs.issue-number }}/head

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
#    - name: Set ref to checkout
#      run: |
#         if [ ${{ github.event_name }} == 'push' ]; then
#          ref=${{ github.ref }}
#         else
#          ref=refs/pull/${{ github.event.inputs.issue-number }}/head
#         fi
#         echo "REF=$ref" >> $GITHUB_ENV
#
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v3
      
    - name: Setup
      uses: ./.github/actions/env_setup
      with:
        event_name: ${{ github.event_name }}
        issue_number: ${{ github.event.inputs.issue-number }}
        az_workspace: ${{ github.event.inputs.az-workspace }}
        az_resource_group: ${{ github.event.inputs.az-resource-group }}

      # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Connect or Create a Compute Target in Azure Machine Learning
    - name: Connect/Create Azure Machine Learning Compute Target
      id: aml_compute_training
      uses: Azure/aml-compute@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Submit a training run to the Azure Machine Learning
    - name: Submit training run
      id: aml_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "${{ steps.aml_run.outputs.run_metrics }}"
    
    # Register model in Azure Machine Learning model registry
    - name: Register model
      id: aml_registermodel
      uses: Azure/aml-registermodel@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          run_id:  ${{ steps.aml_run.outputs.run_id }}
          experiment_name: ${{ steps.aml_run.outputs.experiment_name }}

    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "${{ steps.aml_registermodel.outputs.model_id }}"
